name: main

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure and call API
        env:
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
        run: |
          echo "Using the API Key"
          python -c "import os; print(os.getenv('GENAI_API_KEY'))"
