name: main

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Gemini API
        env:
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}  # Pass the secret as an environment variable
        run: |
          echo "Configuring Gemini API..."
          python -c "import os; import genai; genai.configure(api_key=os.getenv('GENAI_API_KEY'))"
