name: Python CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          echo "Upgrading pip"
          python -m pip install --upgrade pip
          echo "Installing genai"
          pip install genai  # Ensure genai is installed
          echo "Installed packages:"
          pip list  # List installed packages to confirm

      - name: Test API Key and import
        env:
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
        run: |
          echo "Using the API Key"
          curl \
            -H 'Content-Type: application/json' \
            -d '{"contents":[{"parts":[{"text":"Explain how AI works"}]}]}' \
            -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=os.getenv('GENAI_API_KEY')'
